
variables:
  GIT_CLEAN_FLAGS: none

stages:
  - clang-format
  - build_linux
  - build_windows
  - build_macOS
  - build_webGL
#   - unit-tests


image: unityci/editor:ubuntu-2022.3.28f1-base-3.1.0

build_linux:
  stage: build_linux
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - echo "$UNITY_CERT" > ./Unity_v2020.x.ulf
    - unity-editor -quit -batchmode -quit -manualLicenseFile ./Unity_v2020.x.ulf || true
  script:
    - mkdir -p $CI_PROJECT_DIR/linux_build
    - unity-editor  -quit -batchmode -job-worker-count 8 -projectPath $CI_PROJECT_DIR -buildLinux64Player $CI_PROJECT_DIR/linux_build/build.x86_64 -logFile debug/log.txt
  artifacts:
    paths:
      - $CI_PROJECT_DIR/linux_build/
    expire_in: 1 week
  # Enable for debug
  # artifacts:
  #   when: on_failure
  #   paths:
  #     - debug/

build_windows:
  image:  unityci/editor:ubuntu-2022.3.28f1-windows-mono-3.1.0
  stage: build_windows
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - echo "$UNITY_CERT" > ./Unity_v2020.x.ulf
    - unity-editor  -quit -batchmode -quit -manualLicenseFile ./Unity_v2020.x.ulf || true
  script:
    - mkdir -p $CI_PROJECT_DIR/windows_build
    - unity-editor -quit -batchmode -job-worker-count 8 -projectPath $CI_PROJECT_DIR -buildWindows64Player $CI_PROJECT_DIR/windows_build/build.exe
  artifacts:
    paths:
      - $CI_PROJECT_DIR/windows_build/
    expire_in: 1 week

build_macOS:
  image:  unityci/editor:ubuntu-2022.3.28f1-mac-mono-3.1.0
  stage: build_macOS
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - echo "$UNITY_CERT" > ./Unity_v2020.x.ulf
    - unity-editor -nographics -quit -batchmode -quit -manualLicenseFile ./Unity_v2020.x.ulf || true
  script:
    - mkdir -p $CI_PROJECT_DIR/mac_build
    - unity-editor -nographics -quit -job-worker-count 8 -batchmode -projectPath $CI_PROJECT_DIR -buildOSXUniversalPlayer $CI_PROJECT_DIR/mac_build/build.app 
  artifacts:
    paths:
      - $CI_PROJECT_DIR/mac_build/
    expire_in: 1 week


build_webgl:
  image:  unityci/editor:ubuntu-2022.3.28f1-webgl-3.1.0
  stage: build_webGL
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - echo "$UNITY_CERT" > ./Unity_v2020.x.ulf
    - unity-editor -nographics -quit -batchmode -quit -manualLicenseFile ./Unity_v2020.x.ulf || true
  script:
    - mkdir -p $CI_PROJECT_DIR/webgl_build
    # Limit to 2 jobs as it can crash the build server
    - unity-editor -nographics -job-worker-count 2 -quit -batchmode -projectPath $CI_PROJECT_DIR -executeMethod WebGLBuilder.build
    - cp webgl/index.html $CI_PROJECT_DIR/webgl_build/Beeverse/index.html
  artifacts:
    paths:
      - $CI_PROJECT_DIR/webgl_build/
    expire_in: 1 week

#clang-format:
#  image: ubuntu:latest
#  retry:
#    max: 2
#    when: runner_system_failure
#  before_script: 
#    - apt-get -qq update && apt-get -qq install clang-format-14
#  stage: clang-format
#  needs: []
#  script:
#    - clang-format-14 -i --dry-run `find -type f -name "*.cs" | grep -v Library` -Werror -style=file
